/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package az.orient.hospital.gui;

import az.orient.hospital.model.Department;
import az.orient.hospital.model.Employee;
import az.orient.hospital.model.Item;
import az.orient.hospital.service.HospitalService;
import java.awt.Toolkit;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author EAAbduyev
 */
public class EditEmployeeFrame extends javax.swing.JFrame {

    /**
     * Creates new form EditEmployeeFrame
     */
    private HospitalService hService;
    private int selectedRow;
    
    public EditEmployeeFrame() {
        initComponents();
        setIcon();
    }

    public EditEmployeeFrame(int selectedRow, HospitalService hService) {
        initComponents();
        setIcon();
        this.hService = hService;
        this.selectedRow = selectedRow;
        showOldData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        surnameTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        genderCmb = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        phoneTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        emailTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        deptCmb = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        ctgTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        salaryTxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        bonusTxt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressTxt = new javax.swing.JTextArea();
        editBtn = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        activeTxt = new javax.swing.JTextField();
        dobPicker = new com.toedter.calendar.JDateChooser();
        hirePicker = new com.toedter.calendar.JDateChooser();
        firePicker = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Employee");

        jLabel1.setText("Name:");

        jLabel2.setText("Surname:");

        jLabel3.setText("Gender:");

        genderCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Gender", "male", "female", "not specified" }));

        jLabel4.setText("Birth Date:");

        jLabel5.setText("Phone:");

        jLabel6.setText("Email:");

        jLabel7.setText("Department:");

        deptCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Department" }));

        jLabel8.setText("Category:");

        jLabel9.setText("Hire Date:");

        jLabel10.setText("Fire Date:");

        jLabel11.setText("Salary:");

        jLabel12.setText("Bonus:");

        jLabel13.setText("Address:");

        addressTxt.setColumns(20);
        addressTxt.setRows(5);
        jScrollPane1.setViewportView(addressTxt);

        editBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\img\\edit.png")); // NOI18N
        editBtn.setText("Edit");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        jLabel14.setText("Activity:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(surnameTxt)
                    .addComponent(genderCmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nameTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(phoneTxt)
                    .addComponent(emailTxt)
                    .addComponent(deptCmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ctgTxt)
                    .addComponent(salaryTxt)
                    .addComponent(bonusTxt)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(activeTxt)
                    .addComponent(dobPicker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hirePicker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(firePicker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(surnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(genderCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(dobPicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(phoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(deptCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(ctgTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addComponent(jLabel9))
                    .addComponent(hirePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(firePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(salaryTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(bonusTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(activeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        try {
            Item deptCombo = (Item) deptCmb.getSelectedItem();
            Employee emp = new Employee();
            Department dept = new Department();
            dept.setId(deptCombo.getId());
            emp.setEmp_department(dept);
            emp.setEmp_name(nameTxt.getText());
            emp.setEmp_surname(surnameTxt.getText());
            emp.setEmp_gender((String) genderCmb.getSelectedItem());
            emp.setEmp_dob(dobPicker.getDate());
            emp.setEmp_phone(phoneTxt.getText());
            emp.setEmp_address(addressTxt.getText());
            emp.setEmp_salary(Double.parseDouble(salaryTxt.getText()));
            emp.setEmp_email(emailTxt.getText());
            emp.setEmp_bonus(Double.parseDouble(bonusTxt.getText()));
            emp.setEmp_category(ctgTxt.getText());
            emp.setEmp_hire_date(hirePicker.getDate());
            emp.setEmp_fire_date(firePicker.getDate());
            emp.setIsActive(Integer.parseInt(activeTxt.getText()));
            boolean isUpdated = hService.updateEmployee(emp, selectedRow);
            if(isUpdated) {
                JOptionPane.showMessageDialog(null, "Employee has been successfully updated!", "Success", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Patient cannot be updated!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_editBtnActionPerformed

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("doctor.png")));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField activeTxt;
    private javax.swing.JTextArea addressTxt;
    private javax.swing.JTextField bonusTxt;
    private javax.swing.JTextField ctgTxt;
    private javax.swing.JComboBox<String> deptCmb;
    private com.toedter.calendar.JDateChooser dobPicker;
    private javax.swing.JButton editBtn;
    private javax.swing.JTextField emailTxt;
    private com.toedter.calendar.JDateChooser firePicker;
    private javax.swing.JComboBox<String> genderCmb;
    private com.toedter.calendar.JDateChooser hirePicker;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JTextField phoneTxt;
    private javax.swing.JTextField salaryTxt;
    private javax.swing.JTextField surnameTxt;
    // End of variables declaration//GEN-END:variables

    private void showOldData() {
        try {
            Employee emp = hService.getEmployeeById(selectedRow);
            nameTxt.setText(emp.getEmp_name());
            surnameTxt.setText(emp.getEmp_surname());
            genderCmb.setSelectedItem(emp.getEmp_gender());
            dobPicker.setDate(emp.getEmp_dob());
            phoneTxt.setText(emp.getEmp_phone());
            addressTxt.setText(emp.getEmp_address());
            salaryTxt.setText(Double.toString(emp.getEmp_salary()));
            emailTxt.setText(emp.getEmp_email());
            bonusTxt.setText(Double.toString(emp.getEmp_bonus()));
            ctgTxt.setText(emp.getEmp_category());
            showDeptCombo(emp.getEmp_department().getId(), emp.getEmp_department().getDept_name());
            hirePicker.setDate(emp.getEmp_hire_date());
            firePicker.setDate(emp.getEmp_fire_date());
            activeTxt.setText(Integer.toString(emp.getIsActive()));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void showDeptCombo(int id, String value) {
        try {
            DefaultComboBoxModel deptCmb = (DefaultComboBoxModel) this.deptCmb.getModel();
            List<Department> deptList = hService.getDeptList();
            for(Department dpt: deptList) {
                deptCmb.addElement(new Item(dpt.getId(), dpt.getDept_name()));
            }
            deptCmb.setSelectedItem(new Item(id, value));
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
}
