/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package az.orient.hospital.gui;

import az.orient.hospital.model.Users;
import az.orient.hospital.service.HospitalService;
import az.orient.hospital.service.HospitalServiceAdmin;
import java.awt.Toolkit;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author EAAbduyev
 */
public class LoginFrame extends javax.swing.JFrame {

    private HospitalService hService;
    private HospitalServiceAdmin hServiceAdmin;
    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
        setIcon();
    }
    
    public LoginFrame(HospitalService hService, HospitalServiceAdmin hServiceAdmin) {
        initComponents();
        setIcon();
        this.hService = hService;
        this.hServiceAdmin = hServiceAdmin;
        showLbl.setVisible(false);
        if(passTxtBox.getText().equals("")) {
            showBtn.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        unTxtBox = new javax.swing.JTextField();
        passTxtBox = new javax.swing.JPasswordField();
        loginBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        registerBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        showBtn = new javax.swing.JButton();
        showLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Form");

        jLabel1.setText("UserName:");

        jLabel2.setText("Password:");

        passTxtBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passTxtBoxKeyReleased(evt);
            }
        });

        loginBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\img\\login1.png")); // NOI18N
        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        cancelBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\img\\close.png")); // NOI18N
        cancelBtn.setText("Close");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        registerBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\img\\register.png")); // NOI18N
        registerBtn.setText("Register");
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });

        jLabel3.setText("You do not have an account yet?");

        showBtn.setText("Show Pass");
        showBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showBtnActionPerformed(evt);
            }
        });

        showLbl.setText(".");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(loginBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(unTxtBox, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(passTxtBox, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(showBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cancelBtn)))
                        .addGap(38, 38, 38))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(registerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addComponent(showLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 144, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginBtn)
                    .addComponent(cancelBtn)
                    .addComponent(showBtn))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerBtn)
                    .addComponent(showLbl))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        int dec = JOptionPane.showConfirmDialog(this, "Are you sure to exit?", "Close App", JOptionPane.YES_NO_OPTION);
        if(dec == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        Users user = new Users();
        Users us = new Users();
        user.setUsername(unTxtBox.getText().toLowerCase());
        user.setPassword(passTxtBox.getText());
        
        try {
            us = hService.getUserRole(unTxtBox.getText());
            String role = us.getRole();
            int active = us.getIsActive();
            String fullName = us.getName() + " " + us.getSurname();
            boolean isUser = hService.checkUsers(user);
            if(isUser && role.equals("user")) {
                if(active == 0) {
                    JOptionPane.showMessageDialog(null, "Your user is deleted!", "Deleted User", JOptionPane.OK_OPTION);
                    unTxtBox.setText("");
                    passTxtBox.setText("");
                    unTxtBox.requestFocus();
                } else {
                    MainFrame mainFrame = new MainFrame(hService, role, fullName);
                    mainFrame.setVisible(true);
                    mainFrame.setExtendedState(JFrame.MAXIMIZED_BOTH);
                    mainFrame.setResizable(false);
                    mainFrame.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
                    this.dispose();
                }                
            } else if(isUser && role.equals("admin")) {
                if(active == 0) {
                    JOptionPane.showMessageDialog(null, "Your user is deleted!", "Deleted User", JOptionPane.OK_OPTION);
                    unTxtBox.setText("");
                    passTxtBox.setText("");
                    unTxtBox.requestFocus();
                } else {
                    AdminFrame adminFrame = new AdminFrame(hServiceAdmin, hService, role, fullName);
                    adminFrame.setVisible(true);
                    adminFrame.setExtendedState(JFrame.MAXIMIZED_BOTH);
                    adminFrame.setResizable(false);
                    adminFrame.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
                    this.dispose();
                }                
            } 
            else {
                JOptionPane.showMessageDialog(null, "UserName or Password incorrect!", "Incorrect Priveleges", JOptionPane.OK_OPTION);
                unTxtBox.setText("");
                passTxtBox.setText("");
                unTxtBox.requestFocus();
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        /*
        List<Users> userList = null;
        String un = unTxtBox.getText().toLowerCase();
        String pass = passTxtBox.getText();
        try {
            userList = hService.getUsersList();
            for(Users us: userList) {
                if(un.equals(us.getUsername()) && pass.equals(us.getPassword())) {
                    MainFrame mainFrame = new MainFrame(hService);
                    mainFrame.setVisible(true);
                    mainFrame.setExtendedState(JFrame.MAXIMIZED_BOTH);
                    mainFrame.setResizable(false);
                    mainFrame.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "UserName or Password incorrect!");
                    unTxtBox.setText("");
                    passTxtBox.setText("");
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }*/
    }//GEN-LAST:event_loginBtnActionPerformed

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        this.dispose();
        RegisterFrame registerFrame  = new RegisterFrame(hService);
        registerFrame.setVisible(true);
        registerFrame.setResizable(false);
        registerFrame.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
    }//GEN-LAST:event_registerBtnActionPerformed

    private void passTxtBoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passTxtBoxKeyReleased
        if(!passTxtBox.getText().equals("")) {
            showBtn.setEnabled(true);
        } else {
            showBtn.setEnabled(false);
        }
    }//GEN-LAST:event_passTxtBoxKeyReleased

    private void showBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showBtnActionPerformed
        if(showLbl.getText().equals(".")) {
            passTxtBox.setEchoChar((char)0);
            showLbl.setText("...");
            showBtn.setText("Hide Pass");
        } else {
            passTxtBox.setEchoChar('*');
            showLbl.setText(".");
            showBtn.setText("Show Pass");
        }
    }//GEN-LAST:event_showBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPasswordField passTxtBox;
    private javax.swing.JButton registerBtn;
    private javax.swing.JButton showBtn;
    private javax.swing.JLabel showLbl;
    private javax.swing.JTextField unTxtBox;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("login.gif")));
    }
}
